### ISSUE TITLE
Supporting await / async

### ISSUE THREAD

**Issue by ericlewis** [relay-tools/Relay.swift#35]
As you likely know, concurrency was officially released alongside improvements for SwiftUI such as refreshable. Currently, refreshable relies on the function in its closure be async / awaitable in order for the spinner to "hang around" would be interested in seeing how we could have some sort of "refetch" function for a query that is also possibly async.

**Comment by mjm** [comment]
Yeah, I was just watching the "What's new in SwiftUI" session last night. I think the property wrappers for Relay.swift are gonna need to grow some new APIs for async. I need to dig in a bit more into exactly what APIs there are for managing async tasks to see what the options are there.

**Comment by ericlewis** [comment]
"Discover concurrency in SwiftUI" is a great session to learn more about it too

**Comment by mjm** [comment]
I think the continuation APIs (https://developer.apple.com/documentation/swift/3815002-withunsafecontinuation) are gonna be the key to bridging this gap. They seem to be what let’s you make an async API out of something that isn’t using structured concurrency underneath, which I think is the case here.

**Comment by mjm** [comment]
It looks like this works, at least my limited testing. I've created a `next` branch for changes that only work on the betas, and I've got a feature branch going off of that for async refresh specifically: https://github.com/relay-tools/Relay.swift/compare/next...async-refresh

I've only added it for queries so far, but I think pagination and refetchable fragments will want the same. But for queries, this has a nice benefit of not making you have to manage fetch keys: that happens internally. It might even make sense to deprecate the explicit fetch keys and use the new async function in all cases, I'm not sure.

**Comment by mjm** [comment]
Okay, I think this is working in that branch for refetch and pagination fragments as well as queries. I'm not 100% thrilled about what the implementation looks like, but it's not too bad. I'll merge it into the [next](https://github.com/relay-tools/Relay.swift/tree/next) branch soon.

**Comment by mjm** [comment]
> I'll merge it into the next branch soon.

Hah, well, not sure if over two months later counts as soon, but I've merged it into the `next` branch now.
