### ISSUE TITLE
Allow configuring GC release buffer size

### ISSUE THREAD

**Issue by mjm** [relay-tools/Relay.swift#36]
This came up in #32.

The garbage collector supports keeping a buffer of records that aren't currently being referenced but will still be kept around in case they are needed again. But the size of that buffer is not configurable right now and is always set to 0.

**Comment by ericlewis** [comment]
I'll happily pick this up and test if interested

**Comment by mjm** [comment]
@ericlewis I've pushed a branch [gc-buffer-size](https://github.com/relay-tools/Relay.swift/compare/gc-buffer-size) that makes the buffer size configurable via a new parameter on `Store`'s initializer. If you'd like to try this out, you can point your project at that branch instead of one of the version tags.

The size parameter refers to the number of query operations that will be kept around (have their records still considered in-use and garbage collected) despite no longer being actively retained by a view. So you can probably set this to a pretty low (single-digit) value and see the benefit you want. It is _not_ the number of records that will be kept.

**Comment by mjm** [comment]
This change is now in the main branch.
